### ISSUE TITLE
Where does initial tweet data come from?

### ISSUE THREAD

**Issue by BHunter2889** [valnub/Twitvue-Episode-01#1]
I'm new to Framework7 and Vue and I'm trying to figure out how to integrate my existing app which is intended to display a set of data as a list and sort it based on a selected option from a dropdown search. My problem with this example is I'm not finding where the data is loaded into 'store.js' which appears to be the Tweet data model. It appears this was intended to be a specific set of tweet data and not all tweets related to a users account, but if I got that wrong I apologize. 

Also, apologies if this is addressed in the video. I'm not currently able to watch it but will try to later. Also, given the description of my above app, would it be feasible/easier to implement that without involving Node and other frameworks like Webpack etc? Just plain Vue and Framework7? On a deadline and trying to not get involved with more frameworks if I don't have to. Thanks for any help!

**Comment by valnub** [comment]
Hi, this is a place to post bug reports, not to ask questions. Also, there is no need to ask the same duplicate question twice here and on my blog. However, I've answered your question there.

**Comment by BHunter2889** [comment]
Again, apologies. I didn't realize there was a comment section on your post that was active until after I posted here. Also, I find many useful question threads in GitHub issues on other projects using the question tag, but I understand wanting to keep yours cleaner, so I'm sorry about that. Thanks for responding so promptly!
